### ISSUE TITLE
Add feature able to search words in a pdf

### ISSUE THREAD

**Issue by Saumyavilasroy** [JavaCafe01/PdfViewer#112] opened 2021-03-07 05:51 UTC
### Issue Summary

Not being able to search words in a PDF file 

### Steps to Reproduce the Problem
None

### Specifications

  - App Version:3.6
  - Android Version:10

**Comment by JavaCafe01** [comment] 2021-03-08 03:12
Duplicate of #9

**Closed by JavaCafe01** 2021-03-08 03:12 UTC
