### ISSUE TITLE
PDF is empty when opened via Signal Messenger

### ISSUE THREAD

**Issue by NicoHood** [JavaCafe01/PdfViewer#46] opened 2020-01-14 22:02 UTC
### Issue Summary

I am using PdfViewerPlus v3.2 from the Playstore and Signal v4.52.4 also from the Playstore. When I open a pdf from signal, it is shown empty. This does not happen if I safe it locally and open it via a file browser. This does not happen with other pdf Applications, like "mupdf viewer"

### Steps to Reproduce the Problem

1. Open Signal, select a contact (that also has signal, or use note to yourself)
2. Send him any pdf file (mine was generated using libreoffice export)
3. Open the pdf that you send the other person

### Specifications

  - App Version: 3.2
  - Android Version: 9 (Android One, Xiaomi A2 Lite)

Similar Issues: https://github.com/JavaCafe01/PdfViewer/issues/28

**Comment by Fs00** [comment] 2020-12-21 18:24
Could you guys make sure that Storage permission has been granted to Pdf Viewer Plus and then retry?
Because I get the same issue on Telegram, but only if the app does not have Storage access.

**Comment by Fs00** [comment] 2021-02-21 12:59
I tried to reproduce the bug with the latest version of Signal on Android 9 but it never happened, even if the app didn't have storage permissions.
@JavaCafe01 I think that at this point this issue should be closed. When currently opened PRs will be merged, I'll make some changes to make it clear when the app fails to open the PDF due to an error.

**Closed** 2021-03-08 03:14 UTC
